### ISSUE TITLE
Breakage on null body/struct

### ISSUE THREAD

**Issue by jwolski** [uber/thriftify#34]
...writing tests for param validation in Ringpop and discovered I can't send and verify an error on a null body being sent across the wire.

```
# sends join without required params, regrets it

node_modules/tchannel/node_modules/thriftify/specs/astruct.js:129
        var value = struct[field.name];
                          ^
TypeError: Cannot read property 'app' of null
    at AStruct.uglify (node_modules/tchannel/node_modules/thriftify/specs/astruct.js:129:27)
    at AStruct.toBuffer (node_modules/tchannel/node_modules/thriftify/specs/astruct.js:164:29)
    at TChannelAsThrift.stringify [as _stringify] (node_modules/tchannel/as/thrift.js:345:28)
    at TChannelAsThrift.send (node_modules/tchannel/as/thrift.js:186:32)
    at onIdentified (ringpop/server/index.js:373:31)
    at DefinedEvent.onIdentified [as listener] (node_modules/tchannel/peer.js:220:9)
    at DefinedEvent.emit (node_modules/tchannel/lib/event_emitter.js:86:14)
    at TChannelConnection.onOutIdentified (node_modules/tchannel/connection.js:367:26)
    at DefinedEvent.onOutIdentified [as listener] node_modules/tchannel/connection.js:347:14)
    at DefinedEvent.emit (node_modules/tchannel/lib/event_emitter.js:86:14)
```

Relatively accurate pseudo-test case:

```
var tchannelAsThrift = tchannel.TChannelAsThrift({
  source: <some-source>
});
var request = tchannel.request({
  host: <some-host>,
  hasNoParent: true,
  serviceName: 'ringpop',
  retryLimit: 1,
  trace: false,
  headers: {
    'cn': 'ringpop'
  }
});
tchannelAsThrift.send(request, endpoint, head, null, onSend);

```

**Comment by kriskowal** [comment]
I believe an error, albeit a more informative error, is expected for this case. This is not an operational error, since you are responsible for constructing a valid body for the corresponding Thrift definition.

**Comment by Raynos** [comment]
Agreed. Passing in null for a struct should be an exception.

**Comment by jwolski** [comment]
I see why you'd say that, but isn't the conversion of body to a struct somewhat of a underlying implementation detail to tchannel/as/thrift? As a client, I should be able to send a `null`/empty body if I wish... shouldn't I?

**Comment by Raynos** [comment]
For an outgoing request; you should be able to send null; because that's zero arguments.

So I guess it makes sense to take null for a struct as long as it has zero required fields.

**Comment by jwolski** [comment]
I think tchannel might need to make this a little more explicit.

As a developer building on top of tchannel (as thrift), I'm not thinking that the body is being packed as a Thrift struct (even though the tchannel thrift docs say so). I'm thinking that tchannel wants me to pack the primitives into a body object. If I want to send a 'bad request' with no body I should be able to just as I am able to send a 'bad request' with some missing fields. I dunno. Maybe my expectations are wrong. Should I expect that there is client-side Thrift validation going on too?

**Comment by kriskowal** [comment]
We could alter thriftify to treat null as an empty struct. If there are any required fields on the struct, thriftify would still throw an exception.

The thriftify request handler does bypass the application handler and respond with bad request frames if a request does not meet or exceed the thrift spec’s requirements.

**Comment by Raynos** [comment]
@jwolski 

There are two parts; parsing & serializing; If you pass an invalid data structure to the thrift serializer it will throw an exception.

If tchannel/as/thrift parses an invalid data structure it will warn() and send back a BadRequest.

**Comment by Raynos** [comment]
> Maybe my expectations are wrong. Should I expect that there is client-side Thrift validation going on too?

The serialization is thrift validation; so we do thrift validation in the client; you must make a valid outgoing request as per the thrift IDL or we will throw a programmer exception.
